# Generated by Django 5.2.8 on 2026-02-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_images')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
